/* eslint-disable */

var RESOURCES = {

// font,
  s_font_fnt: "res/font/font.xml",
  s_font_png: "res/font/font.png",

// images,
  s_background_png: "res/images/background.png",
  s_bomb_png: "res/images/bomb.png",
  s_btn_finish_png: "res/images/btn_finish.png",
  s_bullet1_png: "res/images/bullet1.png",
  s_bullet2_png: "res/images/bullet2.png",
  s_enemy1_png: "res/images/enemy1.png",
  s_enemy1_down1_png: "res/images/enemy1_down1.png",
  s_enemy1_down2_png: "res/images/enemy1_down2.png",
  s_enemy1_down3_png: "res/images/enemy1_down3.png",
  s_enemy1_down4_png: "res/images/enemy1_down4.png",
  s_enemy2_png: "res/images/enemy2.png",
  s_enemy2_down1_png: "res/images/enemy2_down1.png",
  s_enemy2_down2_png: "res/images/enemy2_down2.png",
  s_enemy2_down3_png: "res/images/enemy2_down3.png",
  s_enemy2_down4_png: "res/images/enemy2_down4.png",
  s_enemy2_hit_png: "res/images/enemy2_hit.png",
  s_enemy3_down1_png: "res/images/enemy3_down1.png",
  s_enemy3_down2_png: "res/images/enemy3_down2.png",
  s_enemy3_down3_png: "res/images/enemy3_down3.png",
  s_enemy3_down4_png: "res/images/enemy3_down4.png",
  s_enemy3_down5_png: "res/images/enemy3_down5.png",
  s_enemy3_down6_png: "res/images/enemy3_down6.png",
  s_enemy3_hit_png: "res/images/enemy3_hit.png",
  s_enemy3_n1_png: "res/images/enemy3_n1.png",
  s_enemy3_n2_png: "res/images/enemy3_n2.png",
  s_game_loading1_png: "res/images/game_loading1.png",
  s_game_loading2_png: "res/images/game_loading2.png",
  s_game_loading3_png: "res/images/game_loading3.png",
  s_game_pause_nor_png: "res/images/game_pause_nor.png",
  s_game_pause_pressed_png: "res/images/game_pause_pressed.png",
  s_game_resume_nor_png: "res/images/game_resume_nor.png",
  s_game_resume_pressed_png: "res/images/game_resume_pressed.png",
  s_hero1_png: "res/images/hero1.png",
  s_hero2_png: "res/images/hero2.png",
  s_hero_blowup_n1_png: "res/images/hero_blowup_n1.png",
  s_hero_blowup_n2_png: "res/images/hero_blowup_n2.png",
  s_hero_blowup_n3_png: "res/images/hero_blowup_n3.png",
  s_hero_blowup_n4_png: "res/images/hero_blowup_n4.png",
  s_shoot_copyright_png: "res/images/shoot_copyright.png",
  s_ufo1_png: "res/images/ufo1.png",
  s_ufo2_png: "res/images/ufo2.png",

// sound,
  s_achievement_ogg: "res/sound/achievement.ogg",
  s_big_spaceship_flying_ogg: "res/sound/big_spaceship_flying.ogg",
  s_bullet_ogg: "res/sound/bullet.ogg",
  s_button_ogg: "res/sound/button.ogg",
  s_enemy1_down_ogg: "res/sound/enemy1_down.ogg",
  s_enemy2_down_ogg: "res/sound/enemy2_down.ogg",
  s_enemy3_down_ogg: "res/sound/enemy3_down.ogg",
  s_game_music_ogg: "res/sound/game_music.ogg",
  s_game_over_ogg: "res/sound/game_over.ogg",
  s_get_bomb_ogg: "res/sound/get_bomb.ogg",
  s_get_double_laser_ogg: "res/sound/get_double_laser.ogg",
  s_out_porp_ogg: "res/sound/out_porp.ogg",
  s_use_bomb_ogg: "res/sound/use_bomb.ogg"
};
